site:
  title: Games On Whales
  url: https://games-on-whales.github.io
  start_page: wolf::index.adoc
content:
  sources:
    - url: git@github.com:games-on-whales/wolf.git
      branches: [ stable, dev* ]
      start_path: docs
urls:
  html_extension_style: default
  latest_version_segment: stable
  latest_version_segment_strategy: replace
  redirect_facility: static
runtime:
  log:
    #failure_level: warn # TODO: remove failing branches from Wolf
    level: debug
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: css/vendor/tabs.css
      contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css
    - path: js/vendor/tabs.js
      contents: ./node_modules/@asciidoctor/tabs/dist/js/tabs.js
    - path: partials/footer-content.hbs
      contents: ./supplemental-ui/partials/footer-content.hbs
    - path: partials/header-content.hbs
      contents: ./supplemental-ui/partials/header-content.hbs
    - path: css/site-extra.css
      contents: ./supplemental-ui/css/site-extra.css
    - path: partials/footer-scripts.hbs
      contents: |
        <script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/tabs.js"></script>
        {{#if env.SITE_SEARCH_PROVIDER}}
        {{> search-scripts}}
        {{/if}}
    - path: partials/head-styles.hbs
      contents: |
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">
        <link rel="stylesheet" href="{{uiRootPath}}/css/site-extra.css">
asciidoc:
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
    - '@antora/lunr-extension'
