site:
  title: Games On Whales
  start_page: gow::index.adoc
content:
  sources:
    - url: git@github.com:games-on-whales/wolf.git
      branches: main
      start_path: docs
    - url: git@github.com:games-on-whales/gow.git
      branches: master
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-kroki
antora:
  extensions:
    - '@antora/lunr-extension'